---
id: MatsueRubyKaigi09
base_name: implement-thread-in-ruby
tags: []
presentation_date: 
version: 1.0.1
licenses: []
slideshare_id: 
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :markdown
  name: Shugo Maeda
  email: shugo@ruby-lang.org
  rubygems_user: shugo
  slideshare_user: ShugoMaeda
  speaker_deck_user: 
